
service: middlend
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  httpApi:
    payload: "2.0"
    cors: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-2:135768707723:table/cs490_backend"


custom:
  pythonRequirements:
    dockerizePip: true
  epsagon:
    token: 96f635aa-225d-4f7c-b24e-1daadf05dc3f
    appName: cs490-middleware

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

plugins:
  - serverless-python-requirements
  - serverless-plugin-epsagon

functions:
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: any
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
