
service: middlend
frameworkVersion: '2'

# Author: Ron Nathaniel
# Release: Beta
# Course: CS 490: 101

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  httpApi:
    payload: "2.0"
    cors: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-2:135768707723:table/cs490_backend"


custom:
  pythonRequirements:
    dockerizePip: true
  epsagon:
    token: 96f635aa-225d-4f7c-b24e-1daadf05dc3f
    appName: cs490-middleware
#  packageExternal
#    external:
#      - '../common'


plugins:
  - serverless-python-requirements
  - serverless-plugin-epsagon
#  - serverless-package-external


functions:
  auth:
    handler: handlers/auth.main
    events:
      - http:
          path: auth
          method: any
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
  create_user:
    handler: handlers/create_user.main
    events:
      - http:
          path: create_user
          method: any
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
  create_post:
    handler: handlers/create_post.main
    events:
      - http:
          path: create_post
          method: any
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
  create_comment:
    handler: handlers/create_comment.main
    events:
      - http:
          path: create_comment
          method: any
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
